# Site settings
title            : Rettungsdecke
email            : rettungsdecke@gmail.com
description      :
  The Rettungsdecke of Jonas Sch√∂ley.
  An interdisciplinary meltdown of science,
  music, bragging and the occasional rant.
baseurl          : ""
url              : "http://jschoeley.github.io"
twitter_username : rettungstweet
github_username  : jschoeley
paginate         : 5
paginate_path    : "/page:num/"
# Build settings
markdown         : redcarpet
highlighter      : pygments
redcarpet        :
  extensions: [smart, strikethrough, superscript, tables]